apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdfserver-api
  namespace: dpc
  labels:
    app: pdfserver-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pdfserver-api
  template:
    metadata:
      labels:
        app: pdfserver-api
    spec:
      containers:
        - name: pdfserver-api
          image: spbdocker03:5000/dpc-pdfgenerator/pdfserver-api:||version||
          ports:
            - containerPort: 80
          env:
          - name: PdfStaticFiles__RootOutputDirectory
            value: /pdfoutput
          - name: ConfigurationService__BaseUrl
            valueFrom:
              configMapKeyRef:
                name: dpc-config
                key: CONFIGURATION_SERVICE_HOST
          - name: ConfigurationService__XAuthToken
            valueFrom:
              configMapKeyRef:
                name: dpc-config
                key: CONFIGURATION_SERVICE_TOKEN
          - name: ConfigurationService__UseConsolidatedApi
            value: 'true'
          - name: DPCApi__BaseUrl
            valueFrom:
              configMapKeyRef:
                name: dpc-config
                key: API_HOST
          - name: DPCApi__UseConsolidatedApi
            value: 'true'
          - name: NodeServer__GenerateBaseUrl
            valueFrom:
              configMapKeyRef:
                name: dpc-config
                key: PDF_LAYOUT_API_HOST          
          - name: NodeServer__OutputBaseUrl
            valueFrom:
              configMapKeyRef:
                name: dpc-config
                key: MEDIA_API_HOST         
---
apiVersion: v1
kind: Service
metadata:
  name: pdfserver-api
  namespace: dpc
spec:
  type: ClusterIP
  selector:
    app: pdfserver-api
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: pdfserver-api
  namespace: dpc
spec:
  rules:
  - host: pdfserver-api.dpc-pdfgenerator.dev.qsupport.ru
    http:
      paths:
      - backend:
          serviceName: pdfserver-api
          servicePort: 80